// <auto-generated />
namespace EIMT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Invoices_Paid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Invoices_Paid));
        
        string IMigrationMetadata.Id
        {
            get { return "201411262039541_Invoices_Paid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
