// <auto-generated />
namespace EIMT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Invoices_paid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Invoices_paid));
        
        string IMigrationMetadata.Id
        {
            get { return "201411262203492_Invoices_paid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
