// <auto-generated />
namespace EIMT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class UserServiceProvider : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserServiceProvider));
        
        string IMigrationMetadata.Id
        {
            get { return "201411262021138_UserServiceProvider"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
